- name: "`Secret/{{ quay_puller_secret_name }}`"
  kubernetes.core.k8s:
    kubeconfig: "{{ ansible_k8s_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ quay_puller_secret_name }}"
        namespace: "{{ inventory_namespace }}"
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: >-
          {{ {"auths": {ansible_quay_hostname: {"auth": _auth}}} | to_json }}
  vars:
    _auth: >-
      {{ (quay_puller_credentials.username ~ ':' ~ quay_puller_credentials.token) | b64encode }}
